--------------------------------------------------------
--  File created - pi¹tek-maja-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIAGNOZY
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."DIAGNOZY" 
   (	"ID" NUMBER, 
	"ID_SAMOCHODU" NUMBER, 
	"UWAGI_KLIENTA" VARCHAR2(200 BYTE), 
	"UWAGI_MECHANIKA" VARCHAR2(200 BYTE), 
	"ID_MECHANIKA" NUMBER, 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FUNKCJA
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."FUNKCJA" 
   (	"ID" NUMBER, 
	"NAZWA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."KLIENCI" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(30 BYTE), 
	"NAZWISKO" VARCHAR2(30 BYTE), 
	"NR_TEL" NUMBER, 
	"ID_UZYTKOWNIKA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW 
  DISTRIBUTE AUTO NO DUPLICATE ;
--------------------------------------------------------
--  DDL for Table KLIENCI_UZYTKOWNICY
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" 
   (	"ID" NUMBER, 
	"LOGIN" VARCHAR2(20 BYTE), 
	"HASLO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."PRACOWNICY" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(30 BYTE), 
	"NAZWISKO" VARCHAR2(30 BYTE), 
	"NR_TEL" NUMBER, 
	"ADRES" VARCHAR2(50 BYTE), 
	"ID_UZYTKOWNIKA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY_UZYTKOWNICY
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" 
   (	"ID" NUMBER, 
	"LOGIN" VARCHAR2(30 BYTE), 
	"HASLO" VARCHAR2(30 BYTE), 
	"ID_FUKCJI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRZEGLADY
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."PRZEGLADY" 
   (	"ID" NUMBER, 
	"ID_SAMOCHODU" NUMBER, 
	"DATA" DATE, 
	"DATA_WAZNOSCI" DATE, 
	"ID_MECHANIKA" NUMBER, 
	"CZY_POZYTYWNY" NUMBER(1,0), 
	"UWAGI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAMOCHODY
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."SAMOCHODY" 
   (	"ID" NUMBER, 
	"MARKA" VARCHAR2(30 BYTE), 
	"MODEL" VARCHAR2(30 BYTE), 
	"POJ_SILNIKA" VARCHAR2(30 BYTE), 
	"ROK" NUMBER, 
	"ID_KLIENTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAMOCHODY_USLUGI
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" 
   (	"ID" NUMBER, 
	"ID_USLUGI" NUMBER, 
	"ID_SAMOCHODU" NUMBER, 
	"ID_MECHANIKA" NUMBER, 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USLUGI
--------------------------------------------------------

  CREATE TABLE "C##WARSZTAT"."USLUGI" 
   (	"ID" NUMBER, 
	"NAZWA" VARCHAR2(30 BYTE), 
	"OPIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##WARSZTAT.DIAGNOZY
SET DEFINE OFF;
Insert into C##WARSZTAT.DIAGNOZY (ID,ID_SAMOCHODU,UWAGI_KLIENTA,UWAGI_MECHANIKA,ID_MECHANIKA,DATA) values ('1','1','Na przegladzie stwierdzono uszkodzony amortyzator: lewy tylny do wymiany.',null,null,to_date('20/03/13','RR/MM/DD'));
REM INSERTING into C##WARSZTAT.FUNKCJA
SET DEFINE OFF;
Insert into C##WARSZTAT.FUNKCJA (ID,NAZWA) values ('1','Mechanik');
Insert into C##WARSZTAT.FUNKCJA (ID,NAZWA) values ('2','Administrator');
REM INSERTING into C##WARSZTAT.KLIENCI
SET DEFINE OFF;
Insert into C##WARSZTAT.KLIENCI (ID,IMIE,NAZWISKO,NR_TEL,ID_UZYTKOWNIKA) values ('1','Piotr','Szmul','795374658','1');
REM INSERTING into C##WARSZTAT.KLIENCI_UZYTKOWNICY
SET DEFINE OFF;
Insert into C##WARSZTAT.KLIENCI_UZYTKOWNICY (ID,LOGIN,HASLO) values ('1','klient','klient');
REM INSERTING into C##WARSZTAT.PRACOWNICY
SET DEFINE OFF;
Insert into C##WARSZTAT.PRACOWNICY (ID,IMIE,NAZWISKO,NR_TEL,ADRES,ID_UZYTKOWNIKA) values ('1','Wojciech','Skrzypek','756473846','Rzeszow Podwislocze 12','1');
Insert into C##WARSZTAT.PRACOWNICY (ID,IMIE,NAZWISKO,NR_TEL,ADRES,ID_UZYTKOWNIKA) values ('2','Karolina','Szpila','657483759','Lezajsk Rynek 4','2');
REM INSERTING into C##WARSZTAT.PRACOWNICY_UZYTKOWNICY
SET DEFINE OFF;
Insert into C##WARSZTAT.PRACOWNICY_UZYTKOWNICY (ID,LOGIN,HASLO,ID_FUKCJI) values ('1','mechanik','mechanik','1');
Insert into C##WARSZTAT.PRACOWNICY_UZYTKOWNICY (ID,LOGIN,HASLO,ID_FUKCJI) values ('2','administrator','administrator','2');
REM INSERTING into C##WARSZTAT.PRZEGLADY
SET DEFINE OFF;
Insert into C##WARSZTAT.PRZEGLADY (ID,ID_SAMOCHODU,DATA,DATA_WAZNOSCI,ID_MECHANIKA,CZY_POZYTYWNY,UWAGI) values ('1','2',to_date('20/05/02','RR/MM/DD'),to_date('21/05/06','RR/MM/DD'),'1','1',null);
Insert into C##WARSZTAT.PRZEGLADY (ID,ID_SAMOCHODU,DATA,DATA_WAZNOSCI,ID_MECHANIKA,CZY_POZYTYWNY,UWAGI) values ('2','1',to_date('20/01/18','RR/MM/DD'),null,'1','0','Wyciek z amortyzatora');
REM INSERTING into C##WARSZTAT.SAMOCHODY
SET DEFINE OFF;
Insert into C##WARSZTAT.SAMOCHODY (ID,MARKA,MODEL,POJ_SILNIKA,ROK,ID_KLIENTA) values ('1','Lexus','IS 200','1988','1997','1');
Insert into C##WARSZTAT.SAMOCHODY (ID,MARKA,MODEL,POJ_SILNIKA,ROK,ID_KLIENTA) values ('2','Dodge','Viper','6198','2013','1');
REM INSERTING into C##WARSZTAT.SAMOCHODY_USLUGI
SET DEFINE OFF;
Insert into C##WARSZTAT.SAMOCHODY_USLUGI (ID,ID_USLUGI,ID_SAMOCHODU,ID_MECHANIKA,DATA) values ('2','2','1','1',to_date('20/05/01','RR/MM/DD'));
Insert into C##WARSZTAT.SAMOCHODY_USLUGI (ID,ID_USLUGI,ID_SAMOCHODU,ID_MECHANIKA,DATA) values ('1','1','1','1',to_date('20/05/05','RR/MM/DD'));
Insert into C##WARSZTAT.SAMOCHODY_USLUGI (ID,ID_USLUGI,ID_SAMOCHODU,ID_MECHANIKA,DATA) values ('3','2','2','1',to_date('20/04/24','RR/MM/DD'));
REM INSERTING into C##WARSZTAT.USLUGI
SET DEFINE OFF;
Insert into C##WARSZTAT.USLUGI (ID,NAZWA,OPIS) values ('1','Wymiana 2 opon','Usluga obejmuje zdjecie kol z jednej osi, wymiane opon i ponowne zalozenie.');
Insert into C##WARSZTAT.USLUGI (ID,NAZWA,OPIS) values ('2','Wymiana oleju','Usluga obejmuje wymiane oleju z filtrem oleju.');
--------------------------------------------------------
--  DDL for Index DIAGNOZY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."DIAGNOZY_PK" ON "C##WARSZTAT"."DIAGNOZY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FUNKCJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."FUNKCJA_PK" ON "C##WARSZTAT"."FUNKCJA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_KONTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."KLIENCI_KONTA_PK" ON "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_KONTA_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."KLIENCI_KONTA_UK1" ON "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."KLIENCI_PK" ON "C##WARSZTAT"."KLIENCI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."KLIENCI_UK1" ON "C##WARSZTAT"."KLIENCI" ("ID_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."PRACOWNICY_PK" ON "C##WARSZTAT"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."PRACOWNICY_UK1" ON "C##WARSZTAT"."PRACOWNICY" ("ID_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_UZYTKOWNICY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY_PK" ON "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_UZYTKOWNICY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY_UK1" ON "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRZEGLADY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."PRZEGLADY_PK" ON "C##WARSZTAT"."PRZEGLADY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAMOCHODY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."SAMOCHODY_PK" ON "C##WARSZTAT"."SAMOCHODY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAMOCHODY_USLUGI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."SAMOCHODY_USLUGI_PK" ON "C##WARSZTAT"."SAMOCHODY_USLUGI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USLUGI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##WARSZTAT"."USLUGI_PK" ON "C##WARSZTAT"."USLUGI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRZEGLADY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."PRZEGLADY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRZEGLADY" MODIFY ("ID_SAMOCHODU" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRZEGLADY" ADD CONSTRAINT "PRZEGLADY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."PRZEGLADY" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNICY_UZYTKOWNICY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" MODIFY ("ID_FUKCJI" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" ADD CONSTRAINT "PRACOWNICY_UZYTKOWNICY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" ADD CONSTRAINT "PRACOWNICY_UZYTKOWNICY_UK1" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENCI_UZYTKOWNICY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" ADD CONSTRAINT "KLIENCI_KONTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" ADD CONSTRAINT "KLIENCI_KONTA_UK1" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNKCJA
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."FUNKCJA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."FUNKCJA" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."FUNKCJA" ADD CONSTRAINT "FUNKCJA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USLUGI
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."USLUGI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."USLUGI" ADD CONSTRAINT "USLUGI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."USLUGI" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."USLUGI" MODIFY ("OPIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SAMOCHODY_USLUGI
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" MODIFY ("ID_USLUGI" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" MODIFY ("ID_SAMOCHODU" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" ADD CONSTRAINT "SAMOCHODY_USLUGI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_UK1" UNIQUE ("ID_UZYTKOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" MODIFY ("NR_TEL" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" MODIFY ("ADRES" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" MODIFY ("ID_UZYTKOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIAGNOZY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."DIAGNOZY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."DIAGNOZY" MODIFY ("ID_SAMOCHODU" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."DIAGNOZY" ADD CONSTRAINT "DIAGNOZY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."DIAGNOZY" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SAMOCHODY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" MODIFY ("POJ_SILNIKA" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" MODIFY ("MARKA" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" MODIFY ("ROK" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" ADD CONSTRAINT "SAMOCHODY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."KLIENCI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI" MODIFY ("NR_TEL" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI" ADD CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##WARSZTAT"."KLIENCI" MODIFY ("ID_UZYTKOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "C##WARSZTAT"."KLIENCI" ADD CONSTRAINT "KLIENCI_UK1" UNIQUE ("ID_UZYTKOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIAGNOZY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."DIAGNOZY" ADD CONSTRAINT "DIAGNOZY_FK1" FOREIGN KEY ("ID_SAMOCHODU")
	  REFERENCES "C##WARSZTAT"."SAMOCHODY" ("ID") ENABLE;
  ALTER TABLE "C##WARSZTAT"."DIAGNOZY" ADD CONSTRAINT "DIAGNOZY_FK2" FOREIGN KEY ("ID_MECHANIKA")
	  REFERENCES "C##WARSZTAT"."PRACOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."KLIENCI" ADD CONSTRAINT "KLIENCI_FK2" FOREIGN KEY ("ID_UZYTKOWNIKA")
	  REFERENCES "C##WARSZTAT"."KLIENCI_UZYTKOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_FK1" FOREIGN KEY ("ID_UZYTKOWNIKA")
	  REFERENCES "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY_UZYTKOWNICY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."PRACOWNICY_UZYTKOWNICY" ADD CONSTRAINT "PRACOWNICY_UZYTKOWNICY_FK1" FOREIGN KEY ("ID_FUKCJI")
	  REFERENCES "C##WARSZTAT"."FUNKCJA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRZEGLADY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."PRZEGLADY" ADD CONSTRAINT "PRZEGLADY_FK1" FOREIGN KEY ("ID_SAMOCHODU")
	  REFERENCES "C##WARSZTAT"."SAMOCHODY" ("ID") ENABLE;
  ALTER TABLE "C##WARSZTAT"."PRZEGLADY" ADD CONSTRAINT "PRZEGLADY_FK2" FOREIGN KEY ("ID_MECHANIKA")
	  REFERENCES "C##WARSZTAT"."PRACOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SAMOCHODY
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."SAMOCHODY" ADD CONSTRAINT "SAMOCHODY_FK1" FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "C##WARSZTAT"."KLIENCI" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SAMOCHODY_USLUGI
--------------------------------------------------------

  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" ADD CONSTRAINT "SAMOCHODY_USLUGI_FK2" FOREIGN KEY ("ID_USLUGI")
	  REFERENCES "C##WARSZTAT"."USLUGI" ("ID") ENABLE;
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" ADD CONSTRAINT "SAMOCHODY_USLUGI_FK3" FOREIGN KEY ("ID_MECHANIKA")
	  REFERENCES "C##WARSZTAT"."PRACOWNICY" ("ID") ENABLE;
  ALTER TABLE "C##WARSZTAT"."SAMOCHODY_USLUGI" ADD CONSTRAINT "SAMOCHODY_USLUGI_FK1" FOREIGN KEY ("ID_SAMOCHODU")
	  REFERENCES "C##WARSZTAT"."SAMOCHODY" ("ID") ENABLE;
